name: testingscreens
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Dart SDK environment
environment:
  sdk: ^3.6.0

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1
  google_fonts: ^6.2.1

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter settings
flutter:
  uses-material-design: true

  # Assets
  assets:
    - images/

  # Fonts (Google Fonts will be used, so no need to add custom font assets)
